# Generated by Django 3.2.7 on 2021-10-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetsConnect', '0003_user_branch_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='Branch_of_Service',
            field=models.CharField(max_length=30),
        ),
    ]
