# Generated by Django 3.2.7 on 2021-10-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VetsConnect', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Branch_of_Service',
            new_name='branch',
        ),
    ]
