# Generated by Django 3.2.7 on 2021-10-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VetsConnect', '0006_rename_branch_of_service_user_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_address',
            new_name='email',
        ),
    ]
