# Generated by Django 3.2.7 on 2021-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetsConnect', '0007_rename_email_address_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wars',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
